# Generated by Django 2.2.4 on 2020-05-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20200515_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='is_mvp',
            new_name='mvp',
        ),
    ]
