# Generated by Django 3.0.6 on 2020-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200515_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='mvp',
            new_name='is_mvp',
        ),
    ]
