# Generated by Django 3.0.6 on 2020-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20200515_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='is_mvp',
            new_name='mvp',
        ),
    ]
